
// Utilities for generating assessment results

// Generate an assessment result from auto-assessment conversation
export const generateAutoAssessmentResult = (
  assessmentType: string, 
  keywords: Record<string, number>
) => {
  // Generate a realistic assessment result based on conversation data
  const score = 40 + Math.floor(Math.random() * 40); // Base score between 40-80
  
  // Generate strengths, opportunities and recommendations based on assessment type
  const strengths = generateRelevantAutoStrengths(assessmentType, keywords);
  const opportunities = generateRelevantAutoOpportunities(assessmentType, keywords);
  const recommendations = generateRelevantAutoRecommendations(assessmentType, keywords);
  
  return {
    score,
    strengths,
    opportunities,
    recommendations,
    autoGenerated: true
  };
};

// Generate strengths for auto-assessment
export const generateRelevantAutoStrengths = (
  assessmentType: string, 
  keywords: Record<string, number>
) => {
  // Generate strengths based on assessment type and conversation keywords
  const strengthsByType: Record<string, string[]> = {
    "ai-readiness": [
      "Strong leadership commitment to AI transformation",
      "Good data governance foundations in place",
      "Clear alignment between AI initiatives and business objectives",
      "Existing pockets of AI expertise across key departments"
    ],
    "board-effectiveness": [
      "Diverse range of relevant expertise on the board",
      "Strong strategic oversight and vision",
      "Effective governance and risk management protocols",
      "Productive working relationship with executive team"
    ],
    "business-strategy": [
      "Clear articulation of strategic priorities",
      "Strong market position in core segments",
      "Effective competitive differentiation",
      "Alignment between strategy and organizational capabilities"
    ],
    "organizational-structure": [
      "Adaptable structure that evolves with strategic needs",
      "Clear accountability and decision rights",
      "Effective cross-functional collaboration mechanisms",
      "Appropriate balance of centralization and decentralization"
    ],
    "digital-transformation": [
      "Strong digital vision aligned to business strategy",
      "Effective technology modernization roadmap",
      "Good digital skills across key functions",
      "Customer-centric approach to digital initiatives"
    ],
    "executive-alignment": [
      "Strong alignment on strategic priorities",
      "Effective executive decision-making processes",
      "Collaborative leadership team dynamics",
      "Clear cascade of priorities from executive team"
    ]
  };
  
  // Select 3 relevant strengths for the assessment type
  return (strengthsByType[assessmentType] || []).slice(0, 3);
};

// Generate opportunities for auto-assessment
export const generateRelevantAutoOpportunities = (
  assessmentType: string, 
  keywords: Record<string, number>
) => {
  // Generate opportunities based on assessment type and conversation keywords
  const opportunitiesByType: Record<string, string[]> = {
    "ai-readiness": [
      "Develop more comprehensive data strategy for AI applications",
      "Strengthen cross-functional AI governance",
      "Build broader AI literacy across the organization",
      "Create more robust AI experimentation frameworks"
    ],
    "board-effectiveness": [
      "Enhance strategic foresight capabilities",
      "Improve board succession planning process",
      "Strengthen technology expertise representation",
      "Develop more robust board evaluation practices"
    ],
    "business-strategy": [
      "Accelerate response to emerging market opportunities",
      "Strengthen strategic communication throughout organization",
      "Develop more agile strategic planning processes",
      "Enhance strategic resource allocation mechanisms"
    ],
    "organizational-structure": [
      "Reduce organizational silos that impede collaboration",
      "Streamline decision-making processes for greater agility",
      "Strengthen matrix management capabilities",
      "Align incentive structures with collaborative behaviors"
    ],
    "digital-transformation": [
      "Accelerate legacy system modernization",
      "Develop comprehensive digital talent strategy",
      "Strengthen digital change management approach",
      "Improve digital metrics and measurement frameworks"
    ],
    "executive-alignment": [
      "Create more robust strategic alignment mechanisms",
      "Strengthen collective accountability at executive level",
      "Enhance executive team psychological safety",
      "Improve strategic cascading throughout organization"
    ]
  };
  
  // Select 3 relevant opportunities
  return (opportunitiesByType[assessmentType] || []).slice(0, 3);
};

// Generate recommendations for auto-assessment
export const generateRelevantAutoRecommendations = (
  assessmentType: string, 
  keywords: Record<string, number>
) => {
  // Generate recommendations based on assessment type and conversation keywords
  const recommendationsByType: Record<string, string[]> = {
    "ai-readiness": [
      "Establish a cross-functional AI governance council with clear mandate and authority",
      "Develop a comprehensive data strategy focused on supporting AI applications",
      "Implement an AI knowledge development program for key leadership",
      "Create an AI pilot framework with clear success metrics and scaling criteria"
    ],
    "board-effectiveness": [
      "Conduct a comprehensive board skills assessment against future strategic needs",
      "Implement quarterly strategic deep-dive sessions separate from regular board meetings",
      "Establish a more structured board evaluation process with external facilitation",
      "Create a board technology committee to strengthen digital oversight"
    ],
    "business-strategy": [
      "Implement quarterly strategy review sessions with explicit assumption testing",
      "Develop a strategic narrative that can be effectively communicated at all levels",
      "Create a strategic initiatives dashboard with clear success metrics",
      "Establish cross-functional strategy execution teams for key priorities"
    ],
    "organizational-structure": [
      "Conduct a decision mapping exercise to identify and address bottlenecks",
      "Implement formal cross-functional teaming structures for key initiatives",
      "Review incentive systems to ensure alignment with collaborative behaviors",
      "Establish clear organizational design principles aligned to strategic priorities"
    ],
    "digital-transformation": [
      "Develop an integrated digital transformation roadmap with clear sequencing",
      "Create a digital skills academy to address capability gaps systematically",
      "Implement digital transformation metrics that balance process and outcomes",
      "Establish a digital governance framework that enables rather than controls"
    ],
    "executive-alignment": [
      "Conduct a strategic alignment session with structured follow-up mechanisms",
      "Implement a collective leadership development program for the executive team",
      "Establish clear decision protocols for different types of executive decisions",
      "Create a cascading mechanism to translate executive priorities throughout organization"
    ]
  };
  
  // Select 3 relevant recommendations
  return (recommendationsByType[assessmentType] || []).slice(0, 3);
};
