
import { FC, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface ChatOverviewDialogProps {
  savedResults: Record<string, any>;
}

const ChatOverviewDialog: FC<ChatOverviewDialogProps> = ({ savedResults }) => {
  const [tab, setTab] = useState('chat');

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="bg-white/10 hover:bg-white/20 text-white border-white/20">
          View Assessment Overview
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px] max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Assessment Results Overview</DialogTitle>
        </DialogHeader>
        
        <Tabs value={tab} onValueChange={setTab} className="w-full mt-4">
          <TabsList className="grid grid-cols-3 mb-6">
            <TabsTrigger value="chat">Chat</TabsTrigger>
            <TabsTrigger value="scores">Scores</TabsTrigger>
            <TabsTrigger value="recommendations">Recommendations</TabsTrigger>
          </TabsList>
          
          <TabsContent value="chat" className="space-y-4">
            <div className="text-sm text-gray-600">
              <p className="mb-3">The AI assistant can help you understand your assessment results by:</p>
              <ul className="list-disc pl-5 space-y-1.5">
                <li>Providing summaries across all assessments</li>
                <li>Explaining specific assessment results</li>
                <li>Recommending action plans based on your results</li>
                <li>Answering questions about organizational development</li>
              </ul>
              
              <p className="mt-4 font-medium">Try asking:</p>
              <ul className="list-disc pl-5 space-y-1.5 text-stratified">
                <li>"Summarize my assessment results"</li>
                <li>"What are my organization's key strengths?"</li>
                <li>"What are our biggest opportunities for improvement?"</li>
                <li>"Tell me about our AI readiness assessment"</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="scores" className="space-y-4">
            <div className="space-y-4">
              {Object.entries(savedResults).map(([type, data]: [string, any]) => (
                <div key={type} className="flex justify-between items-center border-b pb-3">
                  <div className="font-medium flex items-center">
                    {type.replace('-', ' ')}
                    {data.autoGenerated && (
                      <Badge variant="outline" className="ml-2 text-xs">Auto-Generated</Badge>
                    )}
                  </div>
                  <div className={`text-lg font-bold ${data.score >= 70 ? 'text-emerald-600' : data.score >= 50 ? 'text-amber-600' : 'text-red-600'}`}>
                    {data.score}/100
                  </div>
                </div>
              ))}
            </div>
          </TabsContent>
          
          <TabsContent value="recommendations" className="space-y-4">
            <div className="space-y-6">
              {Object.entries(savedResults).map(([type, data]: [string, any]) => (
                <div key={type} className="space-y-2">
                  <h4 className="font-medium text-stratified">{type.replace('-', ' ')}</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm text-gray-700">
                    {data.recommendations.map((rec: string, i: number) => (
                      <li key={i}>{rec}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};

export default ChatOverviewDialog;
