// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnvekxeweqegoxaglptf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhudmVreGV3ZXFlZ294YWdscHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDU4NzcsImV4cCI6MjA2Mzk4MTg3N30.P3LmPoIUQux-Kl2hcwvuIab1jQV52QI14ix8AVopatw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);